### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [d333pav/Python-Life#1]
https://github.com/d333pav/Python-Life/blob/53dcca50fdb800129d11a20f498e9bf990a0e34c/main.py#L1-L10

mylib, l, n, m, k, a. я ни про одно из этих названий не понял, что оно значит.

**Comment by kuzmichevdima** [comment]
https://github.com/d333pav/Python-Life/blob/f2cbd727747c00fed3c6a6c91ba9d57745c8c5bd/Life_Game.py#L36-L37

j1, j2

https://github.com/d333pav/Python-Life/blob/f2cbd727747c00fed3c6a6c91ba9d57745c8c5bd/Life_Game.py#L41
s

https://github.com/d333pav/Python-Life/blob/f2cbd727747c00fed3c6a6c91ba9d57745c8c5bd/Tests.py#L28-L29

f, a


https://github.com/d333pav/Python-Life/blob/f2cbd727747c00fed3c6a6c91ba9d57745c8c5bd/Tests.py#L10

i

и так далее

**Comment by kuzmichevdima** [comment]
https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/main.py#L6

fun

**Comment by kuzmichevdima** [comment]
https://github.com/d333pav/Python-Life/blob/3f2a9136aa67ab8e3a7147fedf7a4891107a1185/Life_Game.py#L45

action-какое действие? elem, new_elem - что за элементы?

**Comment by d333pav** [comment]
Action и выбирает какое действие ему делать, а elem - элемент который сейчас стоит в данной клетке,  а new_elem - тот который мы хотим поставить, это позволяет делать правильный порядок появления новых видов в пустой клетке.
