### ISSUE TITLE
Правильность

### ISSUE THREAD

**Issue by kuzmichevdima** [d333pav/Python-Life#11]
https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/Life_Game.py#L10

https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/Life_Game.py#L12-L13

https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/Life_Game.py#L64

https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/Life_Game.py#L73

ты сдавал в контест текущую версию? Я не понимаю, если всегда количество соседей копируется, то оно значит никогда не уменьшается?

**Comment by d333pav** [comment]
Я создаю словарь с классами, в которых количество соседей обнулено, а потом на каждом шаге присваиваю временному словарю этот обнуленный.

**Comment by kuzmichevdima** [comment]
А зачем? Почему нельзя просто создать пустой словарь?
