### ISSUE TITLE
странный for

### ISSUE THREAD

**Issue by kuzmichevdima** [d333pav/Python-Life#13]
https://github.com/d333pav/Python-Life/blob/66c87e3b95a245e91975cfdb90ab7256f790cf71/Life_Game.py#L71-L75

зачем он нужен? Почему нельзя вызвать просто current_dict[ocean_array[x][y]].action(...) и убрать лишний иф
https://github.com/d333pav/Python-Life/blob/66c87e3b95a245e91975cfdb90ab7256f790cf71/Life_Game.py#L31
? К тому же, этот for почему-то находится внутри цикла 
https://github.com/d333pav/Python-Life/blob/66c87e3b95a245e91975cfdb90ab7256f790cf71/Life_Game.py#L62

**Comment by d333pav** [comment]
Так там же может вовсе не быть рыбы, а мне нужно делать проверку на появление новой рыбы у каждого вида, поэтому цикл. Но я могу вызывать его только в случае пустой клетки.
