### ISSUE TITLE
тесты

### ISSUE THREAD

**Issue by kuzmichevdima** [d333pav/Python-Life#5]
Опять же, выдержка из условия:
Код должен состоять из трех компонент:
библиотека для моделирования
скрипт для запуска моделирования на примере (пример мы приложим)
тесты на проверку правильности работы кода.
Тестов 0

**Comment by kuzmichevdima** [comment]
названия test1, test2 и так далее неинформативны

**Comment by kuzmichevdima** [comment]
Нужны тесты на проверку того, как работает каждый конкретный вид, а не только на общий игровой процесс

**Comment by kuzmichevdima** [comment]
https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/Tests.py#L31-L33
эти 3 строчки копируются везде, в каждом тесте

**Comment by kuzmichevdima** [comment]
https://github.com/d333pav/Python-Life/blob/26255e869fb4b6480914eea2add1835db74cce0f/Tests.py#L10
почему?

**Comment by d333pav** [comment]
потому что в первых трех числах передаются размер океана и количество итераций

**Comment by kuzmichevdima** [comment]
Еще раз,
Нужны тесты на проверку того, как работает каждый конкретный вид, а не только на общий игровой процесс

**Comment by kuzmichevdima** [comment]
Еще раз,
вот эти 3 строчки копируются везде:
https://github.com/d333pav/Python-Life/blob/66c87e3b95a245e91975cfdb90ab7256f790cf71/Tests.py#L31-L33

**Comment by kuzmichevdima** [comment]
https://github.com/d333pav/Python-Life/blob/66c87e3b95a245e91975cfdb90ab7256f790cf71/Tests.py#L43
так передавать размеры теста и количество итераций крайне неудобно. Зачем их записывать в строку? Почему бы не передавать их просто как аргументы?

**Comment by kuzmichevdima** [comment]
нет ни одного теста, где присутствовали бы все виды

**Comment by kuzmichevdima** [comment]
вот эту функцию нужно отдельно протестировать, так как она довольно нетривиальная:
https://github.com/d333pav/Python-Life/blob/3f2a9136aa67ab8e3a7147fedf7a4891107a1185/Life_Game.py#L75
